# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a9ac4385ecbdfd7d5b6f70ed23e7b266c0f3c3ef591394472efb14ad675df026f194ea7a1b13f80aff07429cc121673ccdf390d3ef9d24f3e4fe30abd87fc4

test:
  secret_key_base: 1cd65fd7b5311c1a930fcc10997ea01af78a2039dd0ec668b738dda44409e763e9ff5af4c36046d98a019ec5b815cffab026d54365bbc55ca0206ad6e9d94950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
